name: pokemondb
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: 3.16.9

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.15.4
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.2
  get_it: ^7.6.4
  intl: ^0.19.0
  json_annotation: ^4.8.1
  loading_animation_widget: ^1.2.0+4
  logger: ^2.0.2+1
  lottie: ^3.0.0
  provider: ^6.1.1


dev_dependencies:
  build_runner: ^2.4.7  
  change_app_package_name: ^1.1.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1



flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/jpg/
    - assets/json/

